# Generated by Django 3.2.4 on 2021-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
