# Generated by Django 3.2.4 on 2021-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_students_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Instructor'), (3, 'Student'), (4, 'Head')], default=1, max_length=10),
        ),
    ]
