# Generated by Django 3.2.4 on 2021-08-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_auto_20210822_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Instructor'), (3, 'Student'), (4, 'DepartmentAdmin')], default=1, max_length=10),
        ),
    ]
